apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-time-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-time-app
  template:
    metadata:
      labels:
        app: sample-time-app
    spec:
      containers:
      - name: sample-time-app
        image: docker.io/sandersup/sample-time-app:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sample-time-app-service
spec:
  type: NodePort
  selector:
    app: sample-time-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30000  
